services:
  fastapi:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code
      - fastapi_data:/code/data
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      - DOCKER_ENV=true
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  fastapi_data:
